Fixing bugs
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.